name: geohearo
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python=3.10
  - pandas
  - geopandas
  - scikit-learn-intelex
  - pip:
      - black
      - levenshtein
      - mypy
      - pydantic
      - python-levenshtein
      - rapidfuzz
      - rich
      - thefuzz==0.19.0
      - types-requests
